//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyService.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyService.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap B1122577279 {
            get {
                object obj = ResourceManager.GetObject("B1122577279", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap brakes {
            get {
                object obj = ResourceManager.GetObject("brakes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap brakes_02 {
            get {
                object obj = ResourceManager.GetObject("brakes-02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap brakes1 {
            get {
                object obj = ResourceManager.GetObject("brakes1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap c1 {
            get {
                object obj = ResourceManager.GetObject("c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cool_02 {
            get {
                object obj = ResourceManager.GetObject("cool-02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DB2007AU00875_medium {
            get {
                object obj = ResourceManager.GetObject("DB2007AU00875_medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Eco_Tech_Clutch {
            get {
                object obj = ResourceManager.GetObject("Eco-Tech-Clutch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap engine_02 {
            get {
                object obj = ResourceManager.GetObject("engine-02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_awesome_4_7_0_car_256_0_263135_none {
            get {
                object obj = ResourceManager.GetObject("font-awesome_4-7-0_car_256_0_263135_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_awesome_4_7_0_save_256_0_ffffff_none {
            get {
                object obj = ResourceManager.GetObject("font-awesome_4-7-0_save_256_0_ffffff_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_awesome_4_7_0_sitemap_256_0_263135_none {
            get {
                object obj = ResourceManager.GetObject("font-awesome_4-7-0_sitemap_256_0_263135_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap font_awesome_4_7_0_users_256_0_32c2dd_none {
            get {
                object obj = ResourceManager.GetObject("font-awesome_4-7-0_users_256_0_32c2dd_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foundation_icon_fonts_2015_02_16_dollar_256_0_114499_none {
            get {
                object obj = ResourceManager.GetObject("foundation-icon-fonts_2015-02-16_dollar_256_0_114499_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foundation_icon_fonts_2015_02_16_dollar_256_0_5895bf_none {
            get {
                object obj = ResourceManager.GetObject("foundation-icon-fonts_2015-02-16_dollar_256_0_5895bf_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foundation_icon_fonts_2015_02_16_dollar_256_0_cbb65a_none {
            get {
                object obj = ResourceManager.GetObject("foundation-icon-fonts_2015-02-16_dollar_256_0_cbb65a_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foundation_icon_fonts_2015_02_16_dollar_256_0_d05438_none {
            get {
                object obj = ResourceManager.GetObject("foundation-icon-fonts_2015-02-16_dollar_256_0_d05438_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foundation_icon_fonts_2015_02_16_dollar_256_0_e2ce4c_none {
            get {
                object obj = ResourceManager.GetObject("foundation-icon-fonts_2015-02-16_dollar_256_0_e2ce4c_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icomoon_free_2014_12_23_user_tie_256_0_019fde_none {
            get {
                object obj = ResourceManager.GetObject("icomoon-free_2014-12-23_user-tie_256_0_019fde_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icomoon_free_2014_12_23_user_tie_256_0_263135_none {
            get {
                object obj = ResourceManager.GetObject("icomoon-free_2014-12-23_user-tie_256_0_263135_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icomoon_free_2014_12_23_user_tie_256_0_32c2dd_none {
            get {
                object obj = ResourceManager.GetObject("icomoon-free_2014-12-23_user-tie_256_0_32c2dd_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icomoon_free_2014_12_23_user_tie_256_0_ffffff_none {
            get {
                object obj = ResourceManager.GetObject("icomoon-free_2014-12-23_user-tie_256_0_ffffff_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ionicons_2_0_1_settings_256_0_263135_none {
            get {
                object obj = ResourceManager.GetObject("ionicons_2-0-1_settings_256_0_263135_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ionicons_2_0_1_settings_256_0_32c2dd_none__1_ {
            get {
                object obj = ResourceManager.GetObject("ionicons_2-0-1_settings_256_0_32c2dd_none (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ligature_symbols_2_11_0_human_256_0_263135_none {
            get {
                object obj = ResourceManager.GetObject("ligature-symbols_2-11-0_human_256_0_263135_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ligature_symbols_2_11_0_users_256_0_263135_none {
            get {
                object obj = ResourceManager.GetObject("ligature-symbols_2-11-0_users_256_0_263135_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lubrificant_02 {
            get {
                object obj = ResourceManager.GetObject("Lubrificant-02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap material_icons_3_0_1_business_256_0_32c2dd_none {
            get {
                object obj = ResourceManager.GetObject("material-icons_3-0-1_business_256_0_32c2dd_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap octicons_4_3_0_triangle_left_256_0_ffffff_none {
            get {
                object obj = ResourceManager.GetObject("octicons_4-3-0_triangle-left_256_0_ffffff_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap octicons_4_3_0_triangle_left_256_0_ffffff_none1 {
            get {
                object obj = ResourceManager.GetObject("octicons_4-3-0_triangle-left_256_0_ffffff_none1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Seat_Belt_128 {
            get {
                object obj = ResourceManager.GetObject("Seat_Belt-128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap services_parts {
            get {
                object obj = ResourceManager.GetObject("services parts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sevicePart_02 {
            get {
                object obj = ResourceManager.GetObject("sevicePart-02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stroke_7_1_2_0_tools_256_0_019fde_none {
            get {
                object obj = ResourceManager.GetObject("stroke-7_1-2-0_tools_256_0_019fde_none", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stroke_7_1_2_0_tools_256_0_019fde_none1 {
            get {
                object obj = ResourceManager.GetObject("stroke-7_1-2-0_tools_256_0_019fde_none1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Transmission_02 {
            get {
                object obj = ResourceManager.GetObject("Transmission-02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ukcp2_04 {
            get {
                object obj = ResourceManager.GetObject("ukcp2_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ukcp2_07 {
            get {
                object obj = ResourceManager.GetObject("ukcp2_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
